// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALfTQpZsLSxFvlOTwYB32wMCuPOnXpXWc',
    appId: '1:9955629611:web:284316695b6b8ce142686e',
    messagingSenderId: '9955629611',
    projectId: 'todo-b4b53',
    authDomain: 'todo-b4b53.firebaseapp.com',
    storageBucket: 'todo-b4b53.appspot.com',
    measurementId: 'G-FE95XP9SJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeuw1QtP7zwmVuoJVGb66VgythTPgQxwI',
    appId: '1:9955629611:android:90e3923746e122e442686e',
    messagingSenderId: '9955629611',
    projectId: 'todo-b4b53',
    storageBucket: 'todo-b4b53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwuYUIFjmkHoysg6T9ntxqjKv5un1W8eY',
    appId: '1:9955629611:ios:5214472d49b1c59042686e',
    messagingSenderId: '9955629611',
    projectId: 'todo-b4b53',
    storageBucket: 'todo-b4b53.appspot.com',
    iosClientId: '9955629611-lel2sehnt3n7qe148bj7fm1ic50tf2ce.apps.googleusercontent.com',
    iosBundleId: 'com.blessing.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwuYUIFjmkHoysg6T9ntxqjKv5un1W8eY',
    appId: '1:9955629611:ios:1f7369fa75c924ca42686e',
    messagingSenderId: '9955629611',
    projectId: 'todo-b4b53',
    storageBucket: 'todo-b4b53.appspot.com',
    iosClientId: '9955629611-h9a1icv529i8mpsiqjv4nd3de2vrasab.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
